<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160420170459 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE ddfa_main_domain_model_category CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_feedback CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_language CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location DROP FOREIGN KEY FK_942C630512469DE2");
		$this->addSql("DROP INDEX IDX_942C630512469DE2 ON ddfa_main_domain_model_location");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location DROP category_id, DROP type, DROP name, DROP description, DROP mail, DROP web, DROP facebook, DROP phone, DROP rating, DROP speakerpublic, DROP speakerprivate, DROP image, DROP imagetype, DROP supportwanted, DROP spokenlanguages, DROP published, DROP subcategory, DROP internalcomment, DROP forchildren, DROP initiative_id, DROP event_id, CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE market_entry_id market_entry_id VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE category_id category_id VARCHAR(255) DEFAULT NULL, CHANGE parent_entry_id parent_entry_id VARCHAR(255) DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE ddfa_main_domain_model_category CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_feedback CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_language CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location ADD category_id VARCHAR(255) DEFAULT NULL, ADD type INT NOT NULL, ADD name VARCHAR(255) DEFAULT NULL, ADD description LONGTEXT DEFAULT NULL, ADD mail VARCHAR(255) DEFAULT NULL, ADD web VARCHAR(255) DEFAULT NULL, ADD facebook VARCHAR(255) DEFAULT NULL, ADD phone VARCHAR(255) DEFAULT NULL, ADD rating INT DEFAULT NULL, ADD speakerpublic VARCHAR(255) DEFAULT NULL, ADD speakerprivate VARCHAR(255) DEFAULT NULL, ADD image VARCHAR(255) DEFAULT NULL, ADD imagetype VARCHAR(255) DEFAULT NULL, ADD supportwanted TINYINT(1) DEFAULT NULL, ADD spokenlanguages VARCHAR(255) DEFAULT NULL, ADD published TINYINT(1) DEFAULT NULL, ADD subcategory VARCHAR(255) DEFAULT NULL, ADD internalcomment LONGTEXT DEFAULT NULL, ADD forchildren TINYINT(1) DEFAULT NULL, ADD initiative_id VARCHAR(255) DEFAULT NULL, ADD event_id VARCHAR(255) DEFAULT NULL, CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE market_entry_id market_entry_id VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location ADD CONSTRAINT FK_942C630512469DE2 FOREIGN KEY (category_id) REFERENCES ddfa_main_domain_model_category (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_942C630512469DE2 ON ddfa_main_domain_model_location (category_id)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE parent_entry_id parent_entry_id VARCHAR(255) DEFAULT NULL, CHANGE category_id category_id VARCHAR(255) DEFAULT NULL");
	}
}