<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160419184111 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_tags_join DROP FOREIGN KEY FK_F959C39EE729E5BF");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_targetgroups_join DROP FOREIGN KEY FK_5872508FE729E5BF");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location DROP FOREIGN KEY FK_942C630571F7E88B");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_tags_join DROP FOREIGN KEY FK_F2734308E729E5BF");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_targetgroups_join DROP FOREIGN KEY FK_E86C104AE729E5BF");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location DROP FOREIGN KEY FK_942C6305AB7D9771");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_tags_join DROP FOREIGN KEY FK_F959C39E6552CB89");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_tags_join DROP FOREIGN KEY FK_F27343086552CB89");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location_tags_join DROP FOREIGN KEY FK_5CC386896552CB89");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry_tags_join DROP FOREIGN KEY FK_FF4043C26552CB89");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_targetgroups_join DROP FOREIGN KEY FK_5872508F297EEAF9");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_targetgroups_join DROP FOREIGN KEY FK_E86C104A297EEAF9");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location_targetgroups_join DROP FOREIGN KEY FK_3C0517A0297EEAF9");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry_targetgroups_join DROP FOREIGN KEY FK_7974FA07297EEAF9");
		$this->addSql("DROP TABLE ddfa_main_domain_model_event");
		$this->addSql("DROP TABLE ddfa_main_domain_model_event_tags_join");
		$this->addSql("DROP TABLE ddfa_main_domain_model_event_targetgroups_join");
		$this->addSql("DROP TABLE ddfa_main_domain_model_initiative");
		$this->addSql("DROP TABLE ddfa_main_domain_model_initiative_tags_join");
		$this->addSql("DROP TABLE ddfa_main_domain_model_initiative_targetgroups_join");
		$this->addSql("DROP TABLE ddfa_main_domain_model_location_tags_join");
		$this->addSql("DROP TABLE ddfa_main_domain_model_location_targetgroups_join");
		$this->addSql("DROP TABLE ddfa_main_domain_model_marketentry_tags_join");
		$this->addSql("DROP TABLE ddfa_main_domain_model_marketentry_targetgroups_join");
		$this->addSql("DROP TABLE ddfa_main_domain_model_tag");
		$this->addSql("DROP TABLE ddfa_main_domain_model_targetgroup");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_category CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_feedback CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_language CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("DROP INDEX IDX_942C6305AB7D9771 ON ddfa_main_domain_model_location");
		$this->addSql("DROP INDEX IDX_942C630571F7E88B ON ddfa_main_domain_model_location");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location DROP event_id, DROP initiative_id, CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE category_id category_id VARCHAR(255) DEFAULT NULL, CHANGE market_entry_id market_entry_id VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE category_id category_id VARCHAR(255) DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE ddfa_main_domain_model_event (persistence_object_identifier VARCHAR(40) NOT NULL, category_id VARCHAR(255) DEFAULT NULL, datefrom DATETIME DEFAULT NULL, dateto DATETIME DEFAULT NULL, dateday INT DEFAULT NULL, dateperiodic INT DEFAULT NULL, entry_id VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, web VARCHAR(255) DEFAULT NULL, facebook VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, rating INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, speakerpublic VARCHAR(255) DEFAULT NULL, speakerprivate VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, imagetype VARCHAR(255) DEFAULT NULL, supportwanted TINYINT(1) DEFAULT NULL, spokenlanguages VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, published TINYINT(1) DEFAULT NULL, subcategory VARCHAR(255) DEFAULT NULL, internalcomment LONGTEXT DEFAULT NULL, forchildren TINYINT(1) DEFAULT NULL, INDEX IDX_9D2E328A12469DE2 (category_id), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_event_tags_join (main_actor VARCHAR(255) NOT NULL, main_tag VARCHAR(255) NOT NULL, INDEX IDX_F959C39EE729E5BF (main_actor), INDEX IDX_F959C39E6552CB89 (main_tag), PRIMARY KEY(main_actor, main_tag)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_event_targetgroups_join (main_actor VARCHAR(255) NOT NULL, main_targetgroup VARCHAR(255) NOT NULL, INDEX IDX_5872508FE729E5BF (main_actor), INDEX IDX_5872508F297EEAF9 (main_targetgroup), PRIMARY KEY(main_actor, main_targetgroup)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_initiative (persistence_object_identifier VARCHAR(40) NOT NULL, category_id VARCHAR(255) DEFAULT NULL, entry_id VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, web VARCHAR(255) DEFAULT NULL, facebook VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, rating INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, speakerpublic VARCHAR(255) DEFAULT NULL, speakerprivate VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, imagetype VARCHAR(255) DEFAULT NULL, supportwanted TINYINT(1) DEFAULT NULL, spokenlanguages VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, published TINYINT(1) DEFAULT NULL, subcategory VARCHAR(255) DEFAULT NULL, internalcomment LONGTEXT DEFAULT NULL, forchildren TINYINT(1) DEFAULT NULL, INDEX IDX_F4B3E5EA12469DE2 (category_id), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_initiative_tags_join (main_actor VARCHAR(255) NOT NULL, main_tag VARCHAR(255) NOT NULL, INDEX IDX_F2734308E729E5BF (main_actor), INDEX IDX_F27343086552CB89 (main_tag), PRIMARY KEY(main_actor, main_tag)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_initiative_targetgroups_join (main_actor VARCHAR(255) NOT NULL, main_targetgroup VARCHAR(255) NOT NULL, INDEX IDX_E86C104AE729E5BF (main_actor), INDEX IDX_E86C104A297EEAF9 (main_targetgroup), PRIMARY KEY(main_actor, main_targetgroup)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_location_tags_join (main_actor VARCHAR(255) NOT NULL, main_tag VARCHAR(255) NOT NULL, INDEX IDX_5CC38689E729E5BF (main_actor), INDEX IDX_5CC386896552CB89 (main_tag), PRIMARY KEY(main_actor, main_tag)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_location_targetgroups_join (main_actor VARCHAR(255) NOT NULL, main_targetgroup VARCHAR(255) NOT NULL, INDEX IDX_3C0517A0E729E5BF (main_actor), INDEX IDX_3C0517A0297EEAF9 (main_targetgroup), PRIMARY KEY(main_actor, main_targetgroup)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_marketentry_tags_join (main_actor VARCHAR(255) NOT NULL, main_tag VARCHAR(255) NOT NULL, INDEX IDX_FF4043C2E729E5BF (main_actor), INDEX IDX_FF4043C26552CB89 (main_tag), PRIMARY KEY(main_actor, main_tag)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_marketentry_targetgroups_join (main_actor VARCHAR(255) NOT NULL, main_targetgroup VARCHAR(255) NOT NULL, INDEX IDX_7974FA07E729E5BF (main_actor), INDEX IDX_7974FA07297EEAF9 (main_targetgroup), PRIMARY KEY(main_actor, main_targetgroup)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_tag (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_targetgroup (persistence_object_identifier VARCHAR(40) NOT NULL, entry_id VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event ADD CONSTRAINT FK_9D2E328A12469DE2 FOREIGN KEY (category_id) REFERENCES ddfa_main_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_tags_join ADD CONSTRAINT FK_F959C39E6552CB89 FOREIGN KEY (main_tag) REFERENCES ddfa_main_domain_model_tag (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_tags_join ADD CONSTRAINT FK_F959C39EE729E5BF FOREIGN KEY (main_actor) REFERENCES ddfa_main_domain_model_event (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_targetgroups_join ADD CONSTRAINT FK_5872508F297EEAF9 FOREIGN KEY (main_targetgroup) REFERENCES ddfa_main_domain_model_targetgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_targetgroups_join ADD CONSTRAINT FK_5872508FE729E5BF FOREIGN KEY (main_actor) REFERENCES ddfa_main_domain_model_event (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative ADD CONSTRAINT FK_F4B3E5EA12469DE2 FOREIGN KEY (category_id) REFERENCES ddfa_main_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_tags_join ADD CONSTRAINT FK_F27343086552CB89 FOREIGN KEY (main_tag) REFERENCES ddfa_main_domain_model_tag (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_tags_join ADD CONSTRAINT FK_F2734308E729E5BF FOREIGN KEY (main_actor) REFERENCES ddfa_main_domain_model_initiative (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_targetgroups_join ADD CONSTRAINT FK_E86C104A297EEAF9 FOREIGN KEY (main_targetgroup) REFERENCES ddfa_main_domain_model_targetgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_targetgroups_join ADD CONSTRAINT FK_E86C104AE729E5BF FOREIGN KEY (main_actor) REFERENCES ddfa_main_domain_model_initiative (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location_tags_join ADD CONSTRAINT FK_5CC386896552CB89 FOREIGN KEY (main_tag) REFERENCES ddfa_main_domain_model_tag (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location_tags_join ADD CONSTRAINT FK_5CC38689E729E5BF FOREIGN KEY (main_actor) REFERENCES ddfa_main_domain_model_location (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location_targetgroups_join ADD CONSTRAINT FK_3C0517A0297EEAF9 FOREIGN KEY (main_targetgroup) REFERENCES ddfa_main_domain_model_targetgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location_targetgroups_join ADD CONSTRAINT FK_3C0517A0E729E5BF FOREIGN KEY (main_actor) REFERENCES ddfa_main_domain_model_location (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry_tags_join ADD CONSTRAINT FK_FF4043C26552CB89 FOREIGN KEY (main_tag) REFERENCES ddfa_main_domain_model_tag (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry_tags_join ADD CONSTRAINT FK_FF4043C2E729E5BF FOREIGN KEY (main_actor) REFERENCES ddfa_main_domain_model_marketentry (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry_targetgroups_join ADD CONSTRAINT FK_7974FA07297EEAF9 FOREIGN KEY (main_targetgroup) REFERENCES ddfa_main_domain_model_targetgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry_targetgroups_join ADD CONSTRAINT FK_7974FA07E729E5BF FOREIGN KEY (main_actor) REFERENCES ddfa_main_domain_model_marketentry (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_category CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_feedback CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_language CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location ADD event_id VARCHAR(255) DEFAULT NULL, ADD initiative_id VARCHAR(255) DEFAULT NULL, CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE market_entry_id market_entry_id VARCHAR(255) DEFAULT NULL, CHANGE category_id category_id VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location ADD CONSTRAINT FK_942C630571F7E88B FOREIGN KEY (event_id) REFERENCES ddfa_main_domain_model_event (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location ADD CONSTRAINT FK_942C6305AB7D9771 FOREIGN KEY (initiative_id) REFERENCES ddfa_main_domain_model_initiative (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_942C6305AB7D9771 ON ddfa_main_domain_model_location (initiative_id)");
		$this->addSql("CREATE INDEX IDX_942C630571F7E88B ON ddfa_main_domain_model_location (event_id)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE category_id category_id VARCHAR(255) DEFAULT NULL");
	}
}