<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160419192743 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE ddfa_main_domain_model_category CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_feedback CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_language CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE category_id category_id VARCHAR(255) DEFAULT NULL, CHANGE market_entry_id market_entry_id VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry ADD parent_entry_id VARCHAR(255) DEFAULT NULL, CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE category_id category_id VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry ADD CONSTRAINT FK_23C7669D25FBE593 FOREIGN KEY (parent_entry_id) REFERENCES ddfa_main_domain_model_marketentry (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_23C7669D25FBE593 ON ddfa_main_domain_model_marketentry (parent_entry_id)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE ddfa_main_domain_model_category CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_feedback CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_language CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE market_entry_id market_entry_id VARCHAR(255) DEFAULT NULL, CHANGE category_id category_id VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry DROP FOREIGN KEY FK_23C7669D25FBE593");
		$this->addSql("DROP INDEX IDX_23C7669D25FBE593 ON ddfa_main_domain_model_marketentry");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry DROP parent_entry_id, CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE category_id category_id VARCHAR(255) DEFAULT NULL");
	}
}