<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160823152943 extends AbstractMigration
{

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry ADD certified TINYINT(1) NOT NULL");
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry DROP certified");
    }
}