TYPO3:
  Neos:
    modules:
      DDFA:
        label: 'Afeefa'
        controller: '\TYPO3\Neos\Controller\Module\ManagementController'
        description: 'The Afeefa backend module'
        icon: 'icon-leaf'
        resource: 'TYPO3_Neos_Backend_Module_Management'
        submodules:
          marketEntries:
            label: 'Entry Module'
            controller: '\DDFA\Main\Controller\Module\DDFA\MarketEntriesModuleController'
            description: "This mdule provides all the common usefull management functions to moderate the added entries by users or to add own new ones."
            icon: 'icon-heart'
            resource: 'DDFA_Main_Module_ddfaMarketEntriesModule'
            actions:
              index:
                label: 'View entries'
                title: 'View all entriey in a list'
              add:
                label: 'Add entry'
                title: 'Add a new entry'
          categories:
            label: 'Categories'
            controller: '\DDFA\Main\Controller\Module\DDFA\CategoriesModuleController'
            description: "The DD4all Categories Submodule provides all the usefull management functions to administrate categories like adding, editing, removing and indexing. (nothing left so say...)"
            icon: 'icon-key'
            resource: 'DDFA_Main_Module_ddfaCategoriesModule'
            actions:
              add:
                label: 'Add category'
                title: 'Add a new category'