TYPO3:
  Neos:
    modules:
      DDFA:
        label: 'Afeefa Management'
        controller: '\TYPO3\Neos\Controller\Module\ManagementController'
        description: 'The Afeefa backend module'
        icon: 'icon-leaf'
        resource: 'TYPO3_Neos_Backend_Module_Management'
        submodules:
          marketEntries:
            label: 'Entries'
            controller: '\DDFA\Main\Controller\Module\DDFA\MarketEntriesModuleController'
            description: "The Entries Submodule provides all the usefull management functions to administrate the user added entries of the Afeefa-Market. See the work of the crowd!"
            icon: 'icon-heart'
            resource: 'DDFA_Main_Module_ddfaMarketEntriesModule'
            actions:
              add:
                label: 'Add entry'
                title: 'Add a new entry'
          categories:
            label: 'Categories'
            controller: '\DDFA\Main\Controller\Module\DDFA\CategoriesModuleController'
            description: "The DD4all Categories Submodule provides all the usefull management functions to administrate categories like adding, editing, removing and indexing. (nothing left so say...)"
            icon: 'icon-key'
            resource: 'DDFA_Main_Module_ddfaCategoriesModule'
            actions:
              add:
                label: 'Add category'
                title: 'Add a new category'