TYPO3:
  Neos:
    modules:
      DDFA:
        label: 'DDFA Management'
        controller: '\TYPO3\Neos\Controller\Module\ManagementController'
        description: 'Some DDFA backend modules'
        icon: 'icon-heart-empty'
        resource: 'TYPO3_Neos_Backend_Module_Management'
        submodules:
          ddfaLocationsModule:
            label: 'Locations'
            controller: '\FELIX\Map\Controller\Module\DDFA\LocationsModuleController'
            description: 'description of the "Locations backend module".'
            icon: 'icon-map-marker'
            resource: 'FELIX_Map_Module_ddfaLocationsModule'