TYPO3:
  Neos:
    modules:
      ddfaBackendManagement:
        label: 'DDFA Management'
        controller: '\TYPO3\Neos\Controller\Module\ManagementController'
        description: 'some DDFA management modules'
        resource: 'TYPO3_Neos_Backend_Module_Management'
        submodules:
          simpleplugin:
            label: 'Location module'
            controller: '\FELIX\Map\Controller\BackendController'
            description: "This is the desc of the Simpleplugin backend module."
            resource: 'FELIX_Map_Module_simpleplugin'