<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150510174509 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		$this->addSql("INSERT INTO `ddfa_main_domain_model_language` VALUES ('086b68a7-c101-4922-977b-7d77bb860ac8','ar','ﺎﻠﻋﺮﺒﻳﺓ (Arabic)'),('1ca3f807-e755-4d0e-9382-4a59b73b559c','fa','ﻑﺍﺮﺳی (Persian)'),('4c9d8930-2314-46cb-81b6-85ed154d628a','fr','Français'),('521c1c80-0074-4a7f-a9c2-52c119d7b7c3','en','English'),('a2938e05-3e95-4658-b2d9-3c2fd4d43fe8','de','Deutsch')");

		$this->addSql("ALTER TABLE ddfa_main_domain_model_event CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_tags_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_targetgroups_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_tags_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_targetgroups_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE market_entry_id market_entry_id VARCHAR(255) DEFAULT NULL, CHANGE event_id event_id VARCHAR(255) DEFAULT NULL, CHANGE initiative_id initiative_id VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location_tags_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location_targetgroups_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		$this->addSql("DELETE FROM ddfa_main_domain_model_languages");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_tags_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_event_targetgroups_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_tags_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_targetgroups_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL, CHANGE initiative_id initiative_id VARCHAR(255) DEFAULT NULL, CHANGE market_entry_id market_entry_id VARCHAR(255) DEFAULT NULL, CHANGE event_id event_id VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location_tags_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_location_targetgroups_join CHANGE main_object main_object VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_marketentry CHANGE persistence_object_identifier persistence_object_identifier VARCHAR(40) NOT NULL");
	}
}