<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150501234141 extends AbstractMigration
{

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE UNIQUE INDEX flow_identity_ddfa_main_domain_model_initiative ON ddfa_main_domain_model_initiative (name, mail)");
        $this->addSql("CREATE UNIQUE INDEX flow_identity_ddfa_map_domain_model_inilocation ON ddfa_map_domain_model_inilocation (name, mail)");
        $this->addSql("CREATE UNIQUE INDEX flow_identity_ddfa_main_domain_model_category ON ddfa_main_domain_model_category (name)");
        $this->addSql("CREATE UNIQUE INDEX flow_identity_ddfa_main_domain_model_tag ON ddfa_main_domain_model_tag (name)");
        $this->addSql("CREATE UNIQUE INDEX flow_identity_ddfa_main_domain_model_targetgroup ON ddfa_main_domain_model_targetgroup (name)");
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP INDEX flow_identity_ddfa_main_domain_model_initiative ON ddfa_main_domain_model_initiative");
        $this->addSql("DROP INDEX flow_identity_ddfa_map_domain_model_inilocation ON ddfa_map_domain_model_inilocation");
        $this->addSql("DROP INDEX flow_identity_ddfa_main_domain_model_category ON ddfa_main_domain_model_category");
        $this->addSql("DROP INDEX flow_identity_ddfa_main_domain_model_tag ON ddfa_main_domain_model_tag");
        $this->addSql("DROP INDEX flow_identity_ddfa_main_domain_model_targetgroup ON ddfa_main_domain_model_targetgroup");
    }
}