<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150316192302 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE ddfa_main_domain_model_tag (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_category (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_targetgroup (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_map_domain_model_inilocation (persistence_object_identifier VARCHAR(40) NOT NULL, initiative VARCHAR(40) DEFAULT NULL, openinghours VARCHAR(255) NOT NULL, `long` VARCHAR(255) NOT NULL, lat VARCHAR(255) NOT NULL, street VARCHAR(255) NOT NULL, zip VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, rating INT NOT NULL, scope VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, mail VARCHAR(255) NOT NULL, web VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, INDEX IDX_8539BC4CE115DEFE (initiative), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_map_domain_model_inilocation_tags_join (main_entry VARCHAR(40) NOT NULL, main_tag VARCHAR(40) NOT NULL, INDEX IDX_208C3E887D2E36 (main_entry), INDEX IDX_208C3E6552CB89 (main_tag), PRIMARY KEY(main_entry, main_tag)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_initiative (persistence_object_identifier VARCHAR(40) NOT NULL, speaker VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, mail VARCHAR(255) NOT NULL, web VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_initiative_categories_join (main_owner VARCHAR(40) NOT NULL, main_category VARCHAR(40) NOT NULL, INDEX IDX_AD5B0BB96C3C553A (main_owner), INDEX IDX_AD5B0BB9DF6E08B4 (main_category), PRIMARY KEY(main_owner, main_category)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_initiative_targetgroups_join (main_owner VARCHAR(40) NOT NULL, main_targetgroup VARCHAR(40) NOT NULL, INDEX IDX_E86C104A6C3C553A (main_owner), INDEX IDX_E86C104A297EEAF9 (main_targetgroup), PRIMARY KEY(main_owner, main_targetgroup)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE ddfa_main_domain_model_initiative_tags_join (main_entry VARCHAR(40) NOT NULL, main_tag VARCHAR(40) NOT NULL, INDEX IDX_F2734308887D2E36 (main_entry), INDEX IDX_F27343086552CB89 (main_tag), PRIMARY KEY(main_entry, main_tag)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE ddfa_map_domain_model_inilocation ADD CONSTRAINT FK_8539BC4CE115DEFE FOREIGN KEY (initiative) REFERENCES ddfa_main_domain_model_initiative (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_map_domain_model_inilocation_tags_join ADD CONSTRAINT FK_208C3E887D2E36 FOREIGN KEY (main_entry) REFERENCES ddfa_map_domain_model_inilocation (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_map_domain_model_inilocation_tags_join ADD CONSTRAINT FK_208C3E6552CB89 FOREIGN KEY (main_tag) REFERENCES ddfa_main_domain_model_tag (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_categories_join ADD CONSTRAINT FK_AD5B0BB96C3C553A FOREIGN KEY (main_owner) REFERENCES ddfa_main_domain_model_initiative (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_categories_join ADD CONSTRAINT FK_AD5B0BB9DF6E08B4 FOREIGN KEY (main_category) REFERENCES ddfa_main_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_targetgroups_join ADD CONSTRAINT FK_E86C104A6C3C553A FOREIGN KEY (main_owner) REFERENCES ddfa_main_domain_model_initiative (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_targetgroups_join ADD CONSTRAINT FK_E86C104A297EEAF9 FOREIGN KEY (main_targetgroup) REFERENCES ddfa_main_domain_model_targetgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_tags_join ADD CONSTRAINT FK_F2734308887D2E36 FOREIGN KEY (main_entry) REFERENCES ddfa_main_domain_model_initiative (persistence_object_identifier)");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_tags_join ADD CONSTRAINT FK_F27343086552CB89 FOREIGN KEY (main_tag) REFERENCES ddfa_main_domain_model_tag (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE ddfa_map_domain_model_inilocation_tags_join DROP FOREIGN KEY FK_208C3E6552CB89");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_tags_join DROP FOREIGN KEY FK_F27343086552CB89");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_categories_join DROP FOREIGN KEY FK_AD5B0BB9DF6E08B4");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_targetgroups_join DROP FOREIGN KEY FK_E86C104A297EEAF9");
		$this->addSql("ALTER TABLE ddfa_map_domain_model_inilocation_tags_join DROP FOREIGN KEY FK_208C3E887D2E36");
		$this->addSql("ALTER TABLE ddfa_map_domain_model_inilocation DROP FOREIGN KEY FK_8539BC4CE115DEFE");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_categories_join DROP FOREIGN KEY FK_AD5B0BB96C3C553A");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_targetgroups_join DROP FOREIGN KEY FK_E86C104A6C3C553A");
		$this->addSql("ALTER TABLE ddfa_main_domain_model_initiative_tags_join DROP FOREIGN KEY FK_F2734308887D2E36");
		$this->addSql("DROP TABLE ddfa_main_domain_model_tag");
		$this->addSql("DROP TABLE ddfa_main_domain_model_category");
		$this->addSql("DROP TABLE ddfa_main_domain_model_targetgroup");
		$this->addSql("DROP TABLE ddfa_map_domain_model_inilocation");
		$this->addSql("DROP TABLE ddfa_map_domain_model_inilocation_tags_join");
		$this->addSql("DROP TABLE ddfa_main_domain_model_initiative");
		$this->addSql("DROP TABLE ddfa_main_domain_model_initiative_categories_join");
		$this->addSql("DROP TABLE ddfa_main_domain_model_initiative_targetgroups_join");
		$this->addSql("DROP TABLE ddfa_main_domain_model_initiative_tags_join");
	}
}