-
  name: 'DD4all locations API'
  uriPattern: 'dd4all/locations'
  defaults:
    '@controller': 'Plugin\DDFA\LocationAPI'
    '@action': 'get'
  appendExceedingArguments: false
  httpMethods: ['GET']

-
  name: 'DD4all locations API'
  uriPattern: 'dd4all/locations/{id}'
  defaults:
    '@controller': 'Plugin\DDFA\LocationAPI'
    '@action': 'getById'
  appendExceedingArguments: false
  httpMethods: ['GET']