TYPO3:
  Neos:
    modules:
      DDFA:
        label: 'DDFA Management'
        controller: '\TYPO3\Neos\Controller\Module\ManagementController'
        description: 'Some DDFA backend modules'
        icon: 'icon-heart-empty'
        resource: 'TYPO3_Neos_Backend_Module_Management'
        submodules:
          ddfaLocationsModule:
            label: 'Locations'
            controller: '\DDFA\Map\Controller\Module\DDFA\LocationsModuleController'
            description: "This is the DD4all Locations Modul to magae IniLocations - it's awesome!"
            icon: 'icon-map-marker'
            resource: 'DDFA_Map_Module_ddfaLocationsModule'