-
  name: 'DD4all locations API'
  uriPattern: 'dd4all/locations'
  defaults:
    '@controller': 'Plugin\DDFA\LocationAPI'
  appendExceedingArguments: false
  httpMethods: ['GET']

-
  name: 'DD4all locations API'
  uriPattern: 'dd4all/locations/{inilocation}'
  defaults:
    '@controller': 'Plugin\DDFA\LocationAPI'
    '@action': 'getByLocation'
  appendExceedingArguments: false
  httpMethods: ['GET']
  routeParts:
      inilocation:
        objectType: 'DDFA\Map\Domain\Model\IniLocation'