TYPO3:
  Neos:
    modules:
      DDFA:
        label: 'DD4All Management'
        controller: '\TYPO3\Neos\Controller\Module\ManagementController'
        description: 'The Dresden for All backend module'
        icon: 'icon-leaf'
        resource: 'TYPO3_Neos_Backend_Module_Management'
        submodules:
          locations:
            label: 'Locations'
            controller: '\DDFA\Main\Controller\Module\DDFA\LocationsModuleController'
            description: "The DD4all Locations Submodule provides all the usefull management functions to administrate locations like adding, editing, removing and indexing. (It's awesome!)"
            icon: 'icon-map-marker'
            resource: 'DDFA_Main_Module_ddfaLocationsModule'
            actions:
              add:
                label: 'Add location'
                title: 'Add a new location'
          initiatives:
            label: 'Initiatives'
            controller: '\DDFA\Main\Controller\Module\DDFA\InitiativesModuleController'
            description: "The DD4all Initiatives Submodule provides all the usefull management functions to administrate initiatives like adding, editing, removing and indexing. (pretty awesome as well...)"
            icon: 'icon-bullhorn'
            resource: 'DDFA_Main_Module_ddfaInitiativesModule'
            actions:
              add:
                label: 'Add initiative'
                title: 'Add a new initiative'
          categories:
            label: 'Categories'
            controller: '\DDFA\Main\Controller\Module\DDFA\CategoriesModuleController'
            description: "The DD4all Categories Submodule provides all the usefull management functions to administrate initiatives like adding, editing, removing and indexing. (nothing left so say...)"
            icon: 'icon-key'
            resource: 'DDFA_Main_Module_ddfaCategoriesModule'
            actions:
              add:
                label: 'Add category'
                title: 'Add a new category'
          tags:
            label: 'Tags'
            controller: '\DDFA\Main\Controller\Module\DDFA\TagsModuleController'
            description: "The DD4all Tags Submodule provides all the usefull management functions to administrate initiatives like adding, editing, removing and indexing. (nothing left so say...)"
            icon: 'icon-tags'
            resource: 'DDFA_Main_Module_ddfaTagsModule'
          languages:
            label: 'Languages'
            controller: '\DDFA\Main\Controller\Module\DDFA\LanguagesModuleController'
            description: "The DD4all Languages Submodule provides all the usefull management functions to administrate initiatives like adding, editing, removing and indexing. (nothing left so say...)"
            icon: 'icon-language'
            resource: 'DDFA_Main_Module_ddfaLanguagesModule'